#! /bin/sh
# SPDX-License-Identifier: GPL-2.0-or-later
#
# check ability to run telnet daemon from AVM's telefon daemon
#
errors=0
insert="${1:- }"
#
# we need a symlink as /usr/sbin/telnetd first
#
if ! [ -x /usr/sbin/telnetd ]; then
	printf "Missing symlink for telnet daemon.%s\n" "$insert" 1>&2
	errors=$(( errors + 1 ))
fi
#
# do we have a 'telefon' binary?
#
if ! [ -x /usr/bin/telefon ]; then
	printf "Missing 'telefon' daemon.%s\n" "$insert" 1>&2
	errors=$(( errors + 1 ))
fi
#
# detect variable name needed to activate hidden features
#
if grep -a -q CONFIG_BUILDTYPE /usr/bin/telefon; then
	var="CONFIG_BUILDTYPE"
	val=998
else
	var="CONFIG_RELEASE"
	val=0
fi
#
# '$var=$val' is required to re-enable telnetd functions from 'telefon' daemon
#
if ! grep -q "${var}=$val" /etc/init.d/rc.voip && eval ! [ "\$$var" = "$val" ]; then
	printf "Unable to detect environment setting '%s=%s'.%s\n" "$var" "$val" "$insert" 1>&2
	errors=$(( errors + 1 ))
fi
#
# the flag in 'fx_conf' has to be '0x01' to start the daemon
#
if ! testvalue /var/flash/fx_conf 1 14466 1; then
	printf "The telnet daemon flag in file 'fx_conf' is not set to start this service.%s\n" "$insert" 1>&2
	errors=$(( errors + 1 ))
fi
#
# in case of error, exit here
#
[ $errors -gt 0 ] && exit 1
#
# now check the state of 'telnetd' service
#
if ! pidof telnetd >/dev/null 2>&1 && pidof telefon >/dev/null 2>&1; then
	# telefon daemon is running without telnetd service, but flag is set
	/etc/init.d/rc.voip restart
	/sbin/eventadd 1 "Phone service(s) restarted to enforce 'telnetd' start."
	printf "%sPhone services restarted.%s\n" "$insert" "$insert" 1>&2
fi
exit 0
